spring.application.name=notes-management-backend
server.port=8080
spring.datasource.url=jdbc:h2:mem:notesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
app.cors.allowed-origin=http://localhost:5173
